version: '3'
services:
  concafe_map:
    build: .
    stdin_open: true
    command: /bin/bash
    tty: true
    volumes:
      - .:/app
    ports:
      - ${HOST_WEB_PORT}:8080
    depends_on:
      - "db"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${HOST_DB_PORT}:3306
volumes:
  db-data:
    driver: local