FROM golang:1.17-alpine as builder

RUN mkdir /app
WORKDIR /app

COPY . ./
RUN go mod download
RUN go build .

FROM alpine:3.15
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/concafe_map_mock ./

EXPOSE 8080

CMD [ "./concafe_map_mock" ]