// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ShopGenreRelations string
	ShopGenres         string
	Shops              string
	Staffs             string
}{
	ShopGenreRelations: "shop_genre_relations",
	ShopGenres:         "shop_genres",
	Shops:              "shops",
	Staffs:             "staffs",
}
