// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Shops", testShops)
	t.Run("Staffs", testStaffs)
}

func TestDelete(t *testing.T) {
	t.Run("Shops", testShopsDelete)
	t.Run("Staffs", testStaffsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Shops", testShopsQueryDeleteAll)
	t.Run("Staffs", testStaffsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Shops", testShopsSliceDeleteAll)
	t.Run("Staffs", testStaffsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Shops", testShopsExists)
	t.Run("Staffs", testStaffsExists)
}

func TestFind(t *testing.T) {
	t.Run("Shops", testShopsFind)
	t.Run("Staffs", testStaffsFind)
}

func TestBind(t *testing.T) {
	t.Run("Shops", testShopsBind)
	t.Run("Staffs", testStaffsBind)
}

func TestOne(t *testing.T) {
	t.Run("Shops", testShopsOne)
	t.Run("Staffs", testStaffsOne)
}

func TestAll(t *testing.T) {
	t.Run("Shops", testShopsAll)
	t.Run("Staffs", testStaffsAll)
}

func TestCount(t *testing.T) {
	t.Run("Shops", testShopsCount)
	t.Run("Staffs", testStaffsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Shops", testShopsHooks)
	t.Run("Staffs", testStaffsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Shops", testShopsInsert)
	t.Run("Shops", testShopsInsertWhitelist)
	t.Run("Staffs", testStaffsInsert)
	t.Run("Staffs", testStaffsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("StaffToShopUsingShop", testStaffToOneShopUsingShop)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ShopToStaffs", testShopToManyStaffs)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("StaffToShopUsingStaffs", testStaffToOneSetOpShopUsingShop)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ShopToStaffs", testShopToManyAddOpStaffs)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Shops", testShopsReload)
	t.Run("Staffs", testStaffsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Shops", testShopsReloadAll)
	t.Run("Staffs", testStaffsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Shops", testShopsSelect)
	t.Run("Staffs", testStaffsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Shops", testShopsUpdate)
	t.Run("Staffs", testStaffsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Shops", testShopsSliceUpdateAll)
	t.Run("Staffs", testStaffsSliceUpdateAll)
}
